# Points to note

* torch.rand and torch.randn are different functions

In [1]:
import torch

In [25]:
min_value = 3
max_value = 7
rand_tensor = min_value + torch.rand(5, 3) * (max_value - min_value)

In [26]:
print(rand_tensor)

tensor([[5.9586, 4.6658, 6.1651],
        [4.6778, 4.0342, 6.1776],
        [4.2038, 4.6536, 5.1647],
        [4.0926, 3.5782, 4.9927],
        [5.9286, 5.9042, 4.8658]])


In [34]:
a = torch.rand(3, 3)
print(a)
# add dimension
a.unsqueeze(0)
print(a)
# remove dimension
a.squeeze(0)
print(a)

tensor([[0.6186, 0.3131, 0.7170],
        [0.0759, 0.2206, 0.9423],
        [0.2249, 0.7251, 0.0403]])
tensor([[0.6186, 0.3131, 0.7170],
        [0.0759, 0.2206, 0.9423],
        [0.2249, 0.7251, 0.0403]])
tensor([[0.6186, 0.3131, 0.7170],
        [0.0759, 0.2206, 0.9423],
        [0.2249, 0.7251, 0.0403]])


In [37]:
# create a normal distribution
torch.rand(3,3).normal_()

tensor([[ 0.7381,  0.1509, -0.2820],
        [ 0.2973, -0.2072, -0.5614],
        [-0.2526,  0.4280,  1.6920]])

In [39]:
# retrieve indices of non-zero elements
torch.nonzero(a)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])